name: Sync from Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: deploy
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Print debug info
        run: |
          echo "Current branch:"
          git branch --show-current
          echo "All branches:"
          git branch -a
          
      - name: Sync from main
        run: |
          git fetch origin main
          git merge origin/main --no-edit || (echo "Merge failed" && exit 1)
          git push origin deploy
